##服务端口号
server:
  port: 8001
eureka:
  client:
    service-url:
      ##注册中心地址注册到地址
      defaultZone:  http://localhost:8100/eureka/
    ##需要注册
    register-with-eureka: true
    ##检索服务
    fetch-registry: true

###服务的别名---服务到注册中心的名称
spring:
  application:
    name: app-lhz-order

###支持feign客户端超时时间
###springcloud默认支持ribbon
ribbon:
  ###只建立连接所用的时间，适用网络连接正常状态下，两端连接所用的时间
  ReadTimeout: 5000
  ### 指建立连接后从服务器读取所用的时间
  ConnectTimeout: 5000

###开启hystrix断路器 默认是关闭的 第一种注解是可以使用 类不能使用
feign:
  hystrix:
    enabled: true

###hystrix 禁止超时时间
hystrix:
  command:
    default:
      execution:
        ##timeout:
        ###enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 1000









